#ddev-generated
RUN mkdir -p /opt/fzf && cd /opt/fzf && git init && git remote add origin https://github.com/junegunn/fzf.git && git fetch --depth 1 origin d7d2ac39513f2068f70fbe717d212c9bce8750ed && git checkout FETCH_HEAD && /opt/fzf/install --all && cp /root/.fzf.bash /opt
